[package]
name = "voxelize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tobj = "4.0.0"
glium = "0.32.1"
glam = "*"
nalgebra-glm = "*"
nalgebra = "*"
itertools = "*"
image = "0.24"